# vim:set ft=tmux:

# --> Wombat
set -ogq @thm_bg "#1c1c1c"
set -ogq @thm_fg "#d0d0d0"

# Colors
set -ogq @thm_rosewater "#f2d5cf"
set -ogq @thm_flamingo "#eebebe"
set -ogq @thm_pink "#f4b8e4"
set -ogq @thm_mauve "#c86a44"
set -ogq @thm_red "#ff615a"
set -ogq @thm_maroon "#f58c80"
set -ogq @thm_peach "#e5786d"
set -ogq @thm_yellow "#ebd99c"
set -ogq @thm_green "#b1e969"
set -ogq @thm_teal "#81c8be"
set -ogq @thm_sky "#a5c7ff"
set -ogq @thm_sapphire "#82fff7"
set -ogq @thm_blue "#5da9f6"
set -ogq @thm_lavender "#babbf1"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#a5adce"
set -ogq @thm_subtext_0 "#b5bfe2"
set -ogq @thm_overlay_2 "#949cbb"
set -ogq @thm_overlay_1 "#838ba7"
set -ogq @thm_overlay_0 "#737994"
set -ogq @thm_surface_2 "#626880"
set -ogq @thm_surface_1 "#51576d"
set -ogq @thm_surface_0 "#414559"
set -ogq @thm_mantle "#262626"
set -ogq @thm_crust "#232634"

